### ISSUE TITLE
Optimisation with Stan: Missing optim2.stan

### ISSUE THREAD

**Issue by jmh530** [medewitt/dewitt_blog#1]
Your blog post [Optimisation with Stan](https://michaeldewittjr.com/dewitt_blog/posts/2020-08-27-optimisation-with-stan/) is missing the source for the file optim2.stan.

**Comment by medewitt** [comment]
Available at: https://github.com/medewitt/dewitt_blog/tree/master/_posts/2020-08-27-optimisation-with-stan

Thanks!
